### ISSUE TITLE
Confirm to Paketo RFC00038: Generate SBOM on filesystem

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/composer-install#3]
To implement [Paketo RFC0038](https://github.com/paketo-buildpacks/rfcs/blob/932d89a970bea06c002496dbd6c7e3812ccab788/text/0038-cdx-syft-sbom.md), this buildpack will need to store SBOM information on the filesystem. The RFC outlines what these files are and what they should contain.

The `syft` tool [states that it supports composer](https://github.com/anchore/syft#supported-ecosystems) so we should be able to use [`packit/v2/sbom.Generate`](https://github.com/paketo-buildpacks/packit/blob/b5dff774511ef24f32b949e76bf74beb75c379c4/sbom/sbom.go#L29) to generate an SBOM for an application that manages its dependencies with `composer`.

See also https://github.com/paketo-buildpacks/php/issues/517.

See the [nodejs buildpack integration tests](https://github.com/paketo-buildpacks/node-engine/blob/fb3b4cb3cff25bfa5e3553ad8342420231692bd9/integration/simple_app_test.go#L150-L174) for an example on how to test this.

**Comment by sophiewigmore** [comment]
Note that this is not a part of the PHP rewrite work in https://github.com/paketo-buildpacks/php/issues/485
