### ISSUE TITLE
Composer autoloading not working 

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/composer-install#5]
Copied from PHP Composer: https://github.com/paketo-buildpacks/php-composer/issues/218
This issue is likely still an issue in the new composer-install buildpack, so we should look into this. More details are available on the original issue.

**Comment by sophiewigmore** [comment]
@iainfogg @enumag I realize this is very late, but related https://github.com/paketo-buildpacks/php-composer/issues/218, I  have opened a PR to fix this in the new Composer Install buildpack. I'll come back here and update you when it's been merged in and released for use but wanted to say thank you both for the details and suggestions. It helped a lot!

**Comment by enumag** [comment]
Better late than never. Indeed this should hopefully solve the issue. :-)

**Comment by sophiewigmore** [comment]
@enumag https://github.com/paketo-buildpacks/php/releases/tag/v1.2.0 has the changes!! If you get a chance to try it out, let us know if the changes solve the problem for you.
